name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Java
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Install Maven
        run: |
          sudo apt-get install -y maven

      - name: Build with Maven
        run: mvn clean install

      - name: Set up Docker Compose
        run: |
          sudo apt-get install -y docker-compose

      - name: Start Neo4j and Application with Docker Compose
        run: docker-compose up -d

      - name: Wait for services to be ready
        run: sleep 15  # Adjust as needed based on the time it takes for services to start.

      - name: Run tests or any additional steps
        run: mvn test

      - name: Stop and remove Docker Compose services
        run: docker-compose down
